"""
InsightLoop AI Service — Chat Node: Execute Tools
=================================================
Executes the tool calls generated by the LLM (specifically the vector search)
and appends the results to the message history.
"""

from langchain_core.messages import ToolMessage
from langchain_core.tools import tool

from app.chat.state import ChatState
from app.vector.store import search_with_sources

@tool
def search_feedback(query: str) -> str:
    """Search the customer feedback database using semantic similarity.
    
    Use this tool whenever the user asks about specific feedback content, customer
    opinions, complaints, praise, or anything that requires reading actual responses.
    
    Args:
        query: A specific, descriptive search query based on the TOPIC you're looking
               for — NOT a restatement of the user's question. Use concrete keywords.
               
               GOOD queries:  'staff rude cashier behavior', 'cold food temperature complaint',
                              'complimentary gift freebie reward', 'latte art coffee presentation',
                              'wait time slow service', 'recommend loyalty program'
               BAD queries:   'what do customers think', 'any feedback', 'best response'
               
               For broad questions, make the query specific to one aspect at a time.
               The tool does semantic search, so synonyms and related words work well.
    """
    pass # Tool schema only — actual execution is in execute_tools_node


async def execute_tools_node(state: ChatState) -> dict:
    """
    Executes the tool calls generated by the LLM.
    
    Specifically handles the `search_feedback` tool. It extracts the query,
    performs a Qdrant vector search WITH strict metadata filtering (business_id
    and form_id), and returns the context.
    """
    if state.get("error"):
        return {}

    last_message = state["lc_messages"][-1]
    if not hasattr(last_message, "tool_calls") or not last_message.tool_calls:
        return {}

    sources = state.get("sources", [])
    new_messages = []

    for tool_call in last_message.tool_calls:
        if tool_call["name"] == "search_feedback":
            query = tool_call["args"].get("query", "")
            
            try:
                # Perform the vector search using the robust helper
                # k=8 gives broader recall for edge cases (like a single mention of a gift).
                results = search_with_sources(
                    query=query,
                    business_id=state["business_id"],
                    form_id=state["form_id"],
                    k=8,
                )
                
                if results:
                    context_chunks = []
                    for i, doc in enumerate(results):
                        # Add to sources list for frontend citations
                        # Build a clean source dict that matches the Source Pydantic schema.
                        # snippet = first 200 chars of the prose document (most relevant text).
                        sources.append({
                            "response_id":       doc.metadata.get("response_id", ""),
                            "submitted_at":      doc.metadata.get("submitted_at", ""),
                            "snippet":           doc.page_content[:200],
                            "overall_sentiment": doc.metadata.get("overall_sentiment", ""),
                            "urgency":           doc.metadata.get("urgency", ""),
                            "dominant_topic":    doc.metadata.get("dominant_topic", ""),
                            "is_complaint":      doc.metadata.get("is_complaint", ""),
                            "form_id":           doc.metadata.get("form_id", ""),
                            "business_id":       doc.metadata.get("business_id", ""),
                        })
                        
                        # Build context for LLM
                        metadata_str = (
                            f"Sentiment: {doc.metadata.get('overall_sentiment', 'unknown')} | "
                            f"Urgency: {doc.metadata.get('urgency', 'unknown')} | "
                            f"Submitted: {doc.metadata.get('submitted_at', 'unknown')}"
                        )
                        context_chunks.append(f"[Document {i+1} - {metadata_str}]\n{doc.page_content}")
                    
                    tool_output = "\n\n---\n\n".join(context_chunks)
                else:
                    tool_output = "No matching feedback found for this query."
                    
            except Exception as e:
                print(f"[execute_tools] Vector search failed: {e}")
                tool_output = "Error: Failed to retrieve data."

            # Append the result as a ToolMessage
            new_messages.append(
                ToolMessage(
                    content=tool_output,
                    tool_call_id=tool_call["id"],
                    name=tool_call["name"]
                )
            )

    return {
        "lc_messages": state["lc_messages"] + new_messages,
        "sources": sources
    }
